### ISSUE TITLE
[BACK] Validador de lição - aluno

### ISSUE THREAD

**Issue by RenanLorijola** [ufabc-code/learning-platform#11]

**Comment by RobertChinem** [comment]
Tarefas

- [x] Criar validador de exercício quiz (unitário)
- [x] Criar validador de exercício código (unitário)
- [x] Criar validador do conjunto de exercício de um dado módulo
- [x] CRUD para persistir as respostas dos alunos

**Comment by RobertChinem** [comment]
PR: https://github.com/ufabc-code/learning-platform/pull/15
