### ISSUE TITLE
[FRONT] Visualizador de exercícios de código - aluno

### ISSUE THREAD

**Issue by RenanLorijola** [ufabc-code/learning-platform#8]

**Comment by RobertChinem** [comment]
1 - Exibe a descrição do problema
2 - Exibe um editor de código / entrada / saída com o template básico
3 - Possui uma aba de testes
4 - Possui uma aba de solução

**Comment by RobertChinem** [comment]
PR: https://github.com/ufabc-code/learning-platform/pull/26
PR: https://github.com/ufabc-code/learning-platform/pull/25
